name: bigbrother
description: A new Flutter project.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  built_collection: 5.1.1
  built_value: 8.1.3
  cached_network_image: 3.1.0+1
  cloud_firestore: 2.5.4
  cloud_firestore_web: 2.6.8
  cloud_functions: 3.1.1
  easy_debounce: 2.0.1
  firebase_auth: 3.2.0
  firebase_core: 1.12.0
  firebase_core_web: 1.5.4
  firebase_messaging: 11.2.4
  firebase_messaging_web: 2.2.7
  flutter_lints: 2.0.0
  font_awesome_flutter: 8.11.0
  google_fonts: 2.1.0
  google_sign_in: 5.2.1
  camera: ^0.8.1+3

  cupertino_icons: ^1.0.2
  tflite_flutter: ^0.8.0
  path_provider: ^2.0.1
  path: ^1.8.0
  google_ml_kit: ^0.5.0
  image: ^3.0.2
  sqflite: ^2.0.2
  get_it: ^7.2.0

  intl: 0.17.0
  json_path: 0.2.1
  json_serializable: 6.1.3
  page_transition: 2.0.4
  rxdart: 0.26.0
  shared_preferences: 2.0.11
  sign_in_with_apple:
    git:
      url: https://github.com/asmengistu/dart_packages
      ref: ab18d53a80e0a4bb90f1ad84f37f1b408930f28d
      path: packages/sign_in_with_apple/sign_in_with_apple/
  timeago: 3.1.0
  url_launcher: 6.0.15
  flutter_screenutil: ^5.3.1


dev_dependencies:
  build_runner: 2.1.7
  built_value_generator: 8.1.3

  flutter_test:
    sdk: flutter


  